### PR TITLE
Add :pprint-edn to eval-in

### PR DESCRIPTION
**Pull request by laurentpetit**
- factorized code for runtime-info to emit intermediate datastructure
- use new runtime-info fn from eval-in :pprint (no regression)
- add new flavor eval-in :pprint-edn which pprints everything read-ably

### CODE REVIEW

**Comment by laurentpetit** [comment]
First trial at a proposal for #1956

**Comment by hyPiRion** [comment]
@laurentpetit Terribly sorry for the late response time here. This seems fine by me, but I wonder about one thing: Would it be easier or harder for you to read the output if we were to incorporate the form into the map? Currently it emits two values, which may be slightly awkward to work with.

I have no preference over either, but I would assume embedding the form into the map would be easier to work with for consumers.

**Comment by technomancy** [comment]
Just took a look at this, and it looks great. Unless @laurentpetit wants to make the change to a single form containing both pieces of data, I'd like to go ahead and merge it.

**Comment by laurentpetit** [comment]
Actually, it's so old that I doubt it will be used by Counterclockwise soon. Indeed the project is in maintenance mode, and I'm not working on it anymore.

Anyway, there's still value in the PR so feel free to merge it! Just saying!

**Comment by technomancy** [comment]
OK, thanks.

**Pull request merged**
