### PR TITLE
Address two questions about checkout dependencies

### PR DESCRIPTION
**Pull request by marick**
Two questions I've had, couldn't answer from the leiningen documentation, but found an answer to somewhere else.

### CODE REVIEW

**Comment by technomancy** [comment]
Looks good.  I wonder if the second question could be clearer if we just specified that the directory name in the `checkouts/` directory is completely arbitrary. (Been a while since I've looked at this code, but I think this is true.) Then it's quite clear it doesn't matter what the group-id is.

**Comment by marick** [comment]
I should probably then edit the preceding text. OK?

**Comment by technomancy** [comment]
Sure, that'd work. Thanks.

**Comment by marick** [comment]
I've finished the edits. Note: I left the following alone, because I don't understand it:

"If you change the
dependencies of a checkout project you will still have to run `lein
install` and restart your repl; it's just that source changes will be
picked up immediately."

**Comment by hyPiRion** [comment]
This looks good to me, so I merged it in. I did a small fix on the dependency vector, but otherwise it looked fine.

The sentence you quote attempts to tell you that if you change the dependencies in e.g. the `suchwow` project, then that doesn't propagate down to the project that uses `suchwow` through checkout dependencies. In that case, you have to do `lein install` (and restart the repl) to get those new dependencies downstream.

**Pull request merged**
