### PR TITLE
Leiningen 1899

### LINKED ISSUE #2019: Support Windows "Take Command" alternative shell in lein.bat
I'm using an alternative Windows Shell named "Take Command", not plain CMD.EXE. See [https://jpsoft.com/] (the TCC/LE variant can be downloaded/used free of charge).

I find that two minor amendments are required to make this work _cleanly_ with `lein.bat`
1. One delete command does not redirect stdout, unlike other similar existing uses in `lein.bat`.
2. The classpath does not get set in TCC, simply re-ordering the condition helps.

I'll provide a pull request. Note that these amendments are compatible with CMD.EXE.

### PR DESCRIPTION
**Pull request by m9aertner**
I've worked some more on that script.
Testing (Windows 8, Java 8, normal command shell CMD.EXE, `lein-stable.bat` is `lein.bat` on PATH from stable/2.5.3):

```
cd src
git clone --branch leiningen-1899 https://github.com/m9aertner/leiningen.git "lei nin gen with spaces"
cd "lei nin gen with spaces\leiningen-core"
lein-stable bootstrap
cd ..
bin\lein.bat compile
bin\lein.bat version
bin\lein.bat uberjar
bin\lein.bat self-install

echo %ERRORLEVEL%
rem Note: Error code "2" expected, leiningen-2.6.0-SNAPSHOT-standalone.zip not available on GitHub
```

This script works with Take Command, too, so this commit resolves #2019, too.

### CODE REVIEW

**Comment by m9aertner** [comment]
Duh. Bad condition in line 293. Sorry.

**Comment by m9aertner** [comment]
OK. I think this is fine now.

**Comment by hyPiRion** [comment]
I'd need some help to verify and look over this. @winks? :)

**Comment by winks** [comment]
Yep, I'll try to get to it the next days.

**Comment by winks** [comment]
Awesome, thanks!

**Pull request merged**
