### PR TITLE
Bump Pomegranate version to 1.2.0

### LINKED ISSUE #2567: ‘lein deps :verify’ fails to fetch signatures
`lein deps :verify` reports `:unsigned` for all dependencies, also for artefacts that have been signed:

    :unsigned [ch.gluet/couplet "0.2.0"]

When you add a print statement in the empty catch block [here](https://github.com/technomancy/leiningen/blob/e7d1c1ed96fa7a07c0ce96c0b1d86dacd4336d15/src/leiningen/deps.clj#L71), you can see that Leiningen isn’t able to fetch the signatures:

    #error {                                                            
     :cause Checksum validation failed, no checksums available                                                                                                                      
     :via                                       
     [{:type org.eclipse.aether.resolution.DependencyResolutionException                                                   
       :message Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available
       :at [org.eclipse.aether.internal.impl.DefaultRepositorySystem resolveDependencies DefaultRepositorySystem.java 355]}                                                         
      {:type org.eclipse.aether.resolution.ArtifactResolutionException
       :message Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available
       :at [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolve DefaultArtifactResolver.java 422]}
      {:type org.eclipse.aether.transfer.ArtifactTransferException
       :message Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available
       :at [org.eclipse.aether.connector.basic.ArtifactTransportListener transferFailed ArtifactTransportListener.java 52]}
      {:type org.eclipse.aether.transfer.ChecksumFailureException
       :message Checksum validation failed, no checksums available
       :at [org.eclipse.aether.internal.impl.AbstractChecksumPolicy onNoMoreChecksums AbstractChecksumPolicy.java 67]}]
     :trace
     [[org.eclipse.aether.internal.impl.AbstractChecksumPolicy onNoMoreChecksums AbstractChecksumPolicy.java 67]
      [org.eclipse.aether.connector.basic.ChecksumValidator validate ChecksumValidator.java 107]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner runTask BasicRepositoryConnector.java 459]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner run BasicRepositoryConnector.java 359]
      [org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1 run RunnableErrorForwarder.java 75]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor execute BasicRepositoryConnector.java 590]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector get BasicRepositoryConnector.java 258]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver performDownloads DefaultArtifactResolver.java 498]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolve DefaultArtifactResolver.java 399]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolveArtifacts DefaultArtifactResolver.java 224]
      [org.eclipse.aether.internal.impl.DefaultRepositorySystem resolveDependencies DefaultRepositorySystem.java 338]
      [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
      [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
      [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
      [java.lang.reflect.Method invoke Method.java 498]
      [clojure.lang.Reflector invokeMatchingMethod Reflector.java 167]
      [clojure.lang.Reflector invokeInstanceMethod Reflector.java 102]
      [cemerick.pomegranate.aether$resolve_dependencies_STAR_ invokeStatic aether.clj 806]
      [cemerick.pomegranate.aether$resolve_dependencies_STAR_ doInvoke aether.clj 707]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 665]
      [clojure.core$apply invoke core.clj 660]
      [cemerick.pomegranate.aether$resolve_dependencies invokeStatic aether.clj 815]
      [cemerick.pomegranate.aether$resolve_dependencies doInvoke aether.clj 809]
      [clojure.lang.RestFn invoke RestFn.java 512]
      [leiningen.deps$get_signature invokeStatic deps.clj 64]
      [leiningen.deps$get_signature invoke deps.clj 59]
      [leiningen.deps$verify invokeStatic deps.clj 77]
      [leiningen.deps$verify invoke deps.clj 76]
      [clojure.core$partial$fn__5824 invoke core.clj 2625]
      [leiningen.deps$walk_deps invokeStatic deps.clj 15]
      [leiningen.deps$walk_deps invoke deps.clj 12]
      [leiningen.deps$walk_deps invokeStatic deps.clj 19]
      [leiningen.deps$walk_deps invoke deps.clj 12]
      [leiningen.deps$deps invokeStatic deps.clj 175]
      [leiningen.deps$deps invoke deps.clj 109]
      [clojure.lang.AFn applyToHelper AFn.java 156]
      [clojure.lang.AFn applyTo AFn.java 144]
      [clojure.lang.Var applyTo Var.java 705]
      [clojure.core$apply invokeStatic core.clj 667]
      [clojure.core$apply invoke core.clj 660]
      [leiningen.core.main$partial_task$fn__2041 doInvoke main.clj 284]
      [clojure.lang.RestFn applyTo RestFn.java 139]
      [clojure.lang.AFunction$1 doInvoke AFunction.java 31]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 667]
      [clojure.core$apply invoke core.clj 660]
      [leiningen.core.main$apply_task invokeStatic main.clj 334]
      [leiningen.core.main$apply_task invoke main.clj 320]
      [leiningen.core.main$resolve_and_apply invokeStatic main.clj 343]
      [leiningen.core.main$resolve_and_apply invoke main.clj 336]
      [leiningen.core.main$_main$fn__2130 invoke main.clj 452]
      [leiningen.core.main$_main invokeStatic main.clj 442]
      [leiningen.core.main$_main doInvoke main.clj 439]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.lang.Var applyTo Var.java 705]
      [clojure.core$apply invokeStatic core.clj 665]
      [clojure.main$main_opt invokeStatic main.clj 491]
      [clojure.main$main_opt invoke main.clj 487]
      [clojure.main$main invokeStatic main.clj 598]
      [clojure.main$main doInvoke main.clj 561]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.lang.Var applyTo Var.java 705]
      [clojure.main main main.java 37]]}

But the signature file (including checksums for both the artefact and the signature) exists in the repository: https://repo.clojars.org/ch/gluet/couplet/0.2.0/couplet-0.2.0.jar.asc.

This is on current master (commit e7d1c1ed96fa7a07c0ce96c0b1d86dacd4336d15, Leiningen 2.9.1+), Java 8.

To reproduce, run `lein deps :verify` in a project that has signed dependencies.

### PR DESCRIPTION
**Pull request by glts**
The proposed change bumps the Pomegranate version to 1.2.0. Pomegranate has a new home at clj-commons/pomegranate, hence the change in Maven coordinates.

The version bump constitutes the real fix for #2551 and #2627, and so the workaround in #2551 is no longer necessary and is reverted.

The version bump also fixes #2567, and again an older, related workaround is no longer necessary and is reverted.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks! I think this was the last remaining thing blocking the release of 2.9.2, right?

**Comment by glts** [comment]
@technomancy Absolutely, and in fact this is the conclusion to my streak of bug fixing last summer.

And I was going to ask if you plan a release any time soon? I would welcome one, I think quite a few things got fixed or improved in the past year. Cheers,

**Comment by glts** [comment]
One last thing, leiningen-core/project.clj and leiningen-core/pom.xml both refer to Clojure 1.10.0. It would make sense to bump these to 1.10.1 prior to the release; 1.10.1 is strictly an improvement and shouldn’t break anyone.

**Comment by technomancy** [comment]
Cool; I bumped the Clojure version. Maybe I can do a release in the next week or two.

**Comment by technomancy** [comment]
I think this might be causing #2650; are you seeing the same thing when you deploy?

**Pull request merged**
