### PR TITLE
issue #1944 Fix

### PR DESCRIPTION
**Pull request by shimanekb**
Fixed issue #1944 using std out and err, as suggested.

### CODE REVIEW

**Comment by hyPiRion** [comment]
Whoops, this seems to just bind `*out*` to `*err*`, not including the `(println  (.getMessage t#))` change. Do you think you could replace `(.printStackTrace t#)` with `(println  (.getMessage t#))` in this PR?

You can just add a new commit to this PR, it's not super important to have it in a single commit.

**Comment by shimanekb** [comment]
Sure

**Comment by shimanekb** [comment]
ok, I made the changes.

**Comment by hyPiRion** [comment]
Excellent, thanks!

**Pull request merged**
