### PR TITLE
[#2272] Catch exceptions on malformed profiles.clj files

### PR DESCRIPTION
**Pull request by iperdomo**
Using clojure.edn/read-string results in nil instead of an exception

    user=> (edn/read-string "")
    nil
    user=> (read-string "")
    RuntimeException EOF while reading  clojure.lang.Util.runtimeException (Util.java:221)

### CODE REVIEW

**Comment by iperdomo** [comment]
Not sure why the tests failed. `bin/lein test` works on my local environment ... The full log:

https://gist.github.com/iperdomo/c71ae88e7247e070b331e7b78df9d869

**Comment by technomancy** [comment]
Sorry; I'm afraid we can't change this--clojure.edn/read-string does not
work properly when the file contains read-eval forms. Changing it right
now (even if it's the right thing to do to remove this feature) would be
the wrong time for a breaking change.

**Comment by iperdomo** [comment]
@technomancy yes, i understand that both functions don't have the same semantic.

Would you accept catching the EOF exception instead? It was very unfortunate first issue found by a new Clojure user following a tutorial. Instead of removing the file he removed the content and saved it. After that, the `lein repl` was not working. An experienced Clojure/Java developer understands the stack trace, but it was hard for him to understand why this was failing.

**Comment by technomancy** [comment]
Yes; sorry, I should have been clearer about that. Catching the EOF exception and emitting a sensible error message instead of an enormous stack trace would be great.

**Comment by iperdomo** [comment]
Empty file

    $ echo -n '' > ~/.lein/profiles.clj 
    $ ./bin/lein repl
    Error reading profiles.clj from /home/ivan/.lein
    File cannot be empty
    nREPL server started on port 32793 on host 127.0.0.1 - nrepl://127.0.0.1:32793
    REPL-y 0.3.7, nREPL 0.2.12
    [...]

Invalid content - 1

    $ echo -n '{:user' > ~/.lein/profiles.clj 
    $ ./bin/lein repl
    Error reading profiles.clj from /home/ivan/.lein
    Invalid content was found
    nREPL server started on port 38129 on host 127.0.0.1 - nrepl://127.0.0.1:38129
    REPL-y 0.3.7, nREPL 0.2.12
    [...]

Invalid content - 2

    $ echo -n '{:user}' > ~/.lein/profiles.clj
    $ ./bin/lein repl
    Error reading profiles.clj from /home/ivan/.lein
    Map literal must contain an even number of forms
    nREPL server started on port 33941 on host 127.0.0.1 - nrepl://127.0.0.1:33941
    REPL-y 0.3.7, nREPL 0.2.12

**Comment by iperdomo** [comment]
@technomancy not sure why those test are failing :disappointed: .... they work on one of builds in travis-ci though (https://travis-ci.org/technomancy/leiningen/jobs/231054052)

If you take this changeset, i guess you can squash when merging, so discard the previous attempt.

**Comment by hyPiRion** [comment]
@iperdomo: This has nothing to do with your commit afaict. The issue seems to be cause by the protocol version of TLS from clojars, although I'm not sure why this is the case.

**Comment by iperdomo** [comment]
@hyPiRion ok, good to know

**Comment by technomancy** [comment]
Yeah, these failures are definitely not related to your changes. Thanks!

**Pull request merged**
