### PR TITLE
Fix for issue #2181

### PR DESCRIPTION
**Pull request by webappzero**
Edit file path to match the namespace in the code to fix compilation error in Tutorial example.

### CODE REVIEW

**Comment by webappzero** [comment]
Fixes issue #2181

**Comment by webappzero** [comment]
Not sure this fixes issue.

**Comment by cprice404** [comment]
hrm.  `src/my_stuff/core.clj` seems like the correct path to me, if the namespace inside the clojure file is `my-stuff.core` (which is what it looks like in the examples).  If you were using a namespace of `my.stuff.core`, then the path you use here (`src/my/stuff/core`) would be correct, but it looks to me like the example says `ns my-stuff.core`.

**Comment by webappzero** [comment]
Oops. You and the Tutorial are both correct. Following the instructions more closely I see where I made a mistake. Thank you!

**Pull request closed without merging**
