### PR TITLE
Add "repl :headless :socket PATH" support

### PR DESCRIPTION
**Pull request by rlbdv**
Just for review, I've structured the commits so that the socket test can be run by installing current nrepl 1.0.0-SNAPSHOT, checking out the "Update nrepl to 1.0.0-SNAPSHOT for test-headless-socket" commit, and running `lein test :only leiningen.test.repl/test-headless-socket`.  (Some of the existing tests don't appear to be compatible with the new nrepl.)

The subsequent commits just revert the nrepl version change, and mark that test as `:disabled`.  Before merging, I suspect we may want to squash everything into the first commit, and I'd be happy to do so.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks; I've merged this in b676f29. We can re-enable the test once the new nrepl is released.

**Comment by bbatsov** [comment]
Might be good to also mention this somewhere in the docs.

**Comment by technomancy** [comment]
@bbatsov it's mentioned in the help text for the repl task and also in `sample.project.clj`; is there somewhere else that you had in mind?

**Comment by bbatsov** [comment]
Ah, I totally missed the `sample.project.clj` change. I guess we're good - I just wanted to make sure the end users will be able to find this.

**Pull request closed without merging**
