### PR TITLE
added fix for components.xml merging.  If the description tag contain…

### PR DESCRIPTION
**Pull request by towler73**
…ed embedded html, it needs to be escaped in the resulting merged components.xml.

### CODE REVIEW

**Comment by technomancy** [comment]
I think we can probably do better than hard-coding a list of characters to escape. Surely in that huge pile of libs we pull in this functionality exists already?

**Comment by towler73** [comment]
That's a good point.  Let me look into that.

**Comment by towler73** [comment]
I changed escaping to use commons.lang.StringEscapeUtils.escapeXml().

**Comment by technomancy** [comment]
That looks better; thanks.

**Pull request merged**
