### PR TITLE
Added gpg note for windows users

### PR DESCRIPTION
**Pull request by laforge49**
Instructions for installing and running pinentry agent.

### CODE REVIEW

**Comment by technomancy** [comment]
Can you make "Gpg4win" into a link? Also best to use backticks instead of quotation marks for commands to be run. Thanks.

**Comment by laforge49** [comment]
sure!

**Comment by laforge49** [comment]
Suggested changes applied to the pull request, along with a correction to that same pull request (gpa, not gpg).

**Comment by technomancy** [comment]
Looks good; thanks.

**Pull request merged**
