### PR TITLE
Add support for reader conditional files (cljc) (#1827)

### PR DESCRIPTION
**Pull request by sfnelson**
Clojure 1.7.0 will add support for reader conditionals:

http://dev.clojure.org/display/design/Reader+Conditionals

This patch adds reader conditional support to leiningen, in particular for
compilation (including aot and stale files) and testing.

Before this patch can be merged, [Raynes/bultitude](https://github.com/Raynes/bultitude) needs to release support for resolving namespaces in cljc file, and modify `path-for` in some way as it will no longer be possible to do a 1-to-1 mapping between a namespace and its source file. I've created a merge request for this purpose: https://github.com/Raynes/bultitude/pull/28

Please let me know if there's anything I can do to help get this change accepted. I'm very eager to have this support added as our commercial project requires aot, so we can't use reader conditionals until this is feature is added.

### CODE REVIEW

**Comment by sfnelson** [comment]
Note that the build is failing because of a missing dependency on an updated version of Raynes/bultitude. Once this is available I will update the merge request.

**Comment by Raynes** [comment]
Released.

**Comment by Raynes** [comment]
Note that I did not release a snapshot, obviously.

**Comment by technomancy** [comment]
Thanks for this!

If we could get some Leiningen users to look at this who use `.cljc` files, that would be super helpful. I would like to get a bit more feedback before getting this merged in.

**Comment by bensu** [comment]
Is there a way to try these changes without installing a new version of lein in the whole operating system?

**Comment by technomancy** [comment]
@bensu yeah, check out the "Bootstrapping" section of `CONTRIBUTING.md`.

**Comment by bensu** [comment]
@technomancy thanks!

I tried the patch on a minimal [repo](https://github.com/bensu/cljc-test/) and it didn't work. I might be running `bin/lein` all wrong.

I have both `leiningen` with a fresh copy of `montoux:ft-reader-conditionals` and the test repo, `cljc-test` under the same folder. Then I run
     
     cd leiningen/leiningen-core
     lein bootstrap
     cd ..
     bin/lein compile

     cd ../cljc-test
     ../leiningen/bin/lein test

The results are detailed in this [gist](https://gist.github.com/bensu/5b1045af06ccf925b931)

**Comment by sfnelson** [comment]
Thanks @bensu, I'll take a look. I'll also rebase on HEAD and update the pull request as required.

**Comment by sfnelson** [comment]
@bensu is correct on both points. This change will require leiningen (or more specifically bultitude) to use clojure 1.7's reader to load ns forms. In addition, the bultitude's use of read needs to be adapted -- it needs to add the `:read-cond :allow` option.

I'm happy to make another pull request to bultitude to add the necessary changes, but I'd like some feedback on the feasibility of upgrading leiningen to clojure 1.7.0 on release. Is this a possiblity? Otherwise we'll need to look at using a different reader in bultitude, and possibly elsewhere.

**Comment by sfnelson** [comment]
At present this pull request is not ready to merge or test. I'd like some feedback on the feasibility of switching leiningen to Clojure 1.7.0 when it is released (or possibly a clojure 1.7.0 branch) vs using another reader. Note that other parts of leiningen may be affected, as if we don't switch to 1.7 then cljc files will not be readable by leiningen without eval-in-project.

**Comment by technomancy** [comment]
Is there a tl;dr on any known breaking changes, or is it intended to be a purely backwards-compatible upgrade?

**Comment by sfnelson** [comment]
I'm not aware of any breaking changes

**Comment by lprefontaine** [comment]
Hi guys,

I have an urgent need for this patch. This ain't merged in master yet correct ?

**Comment by damienstanton** [comment]
1.7 has been out for a few weeks now, is there an ETA for when this will be merged into master?

**Comment by lprefontaine** [comment]
If more tests are needed, I can test this against clara-rules tests. We merged most of the code with reader conditionals and I am merging the tests presently. I can run them from CCW/Eclipse but obviously, they need to run with lein :)

**Comment by sfnelson** [comment]
This patch is waiting on a pending pull request to update bultitude to support reading with conditionals enabled (https://github.com/Raynes/bultitude/pull/29) (@raynes). Once that's done I'll update the pull request. This will require leiningen to switch to Clojure 1.7.0, which will require sign off from @technomancy.

**Comment by sfnelson** [comment]
I've updated the pull request to include a commit that updates leiningen to Clojure 1.7.0. I've also fixed the problems observed by @bensu which required another change to bultitude which has been merged (thanks @raynes). The code is ready for review, but testers will probably want to hold off until bultitude is released (probably tomorrow).

I have tested this with our internal projects including a fairly large suite of cljc tests ported from cljx. I had no problems with upgrading leiningen from Clojure 1.6.0 to 1.7.0 with our fairly large internal project but this could certainly benefit from additional testing by other projects.

**Comment by technomancy** [comment]
I have no problem updating Leiningen to 1.7.0 if there aren't any known breaking changes, but think it would be wise to get more people testing this patch before it goes out.

**Comment by lprefontaine** [comment]
I will do so before the end of the week. I do have a work around until this patch gets released but I want to put this behind me this week.
Thank you all

**Comment by sfnelson** [comment]
Pull request is ready for testing

**Comment by bensu** [comment]
I've tried the `montoux/ft-reader-conditionals` on the following projects which have `cljc` test files:

* [zelkova](https://github.com/jamesmacaulay/zelkova)
* [bidi's cljc branch](https://github.com/juxt/bidi/tree/cljc)
* my work's private projects with a fairly complex setup.

and the following tasks:

* `lein test`
* `lein cljsbuild`
* `lein repl`
* `lein doo`

and everything worked.

**Comment by sfnelson** [comment]
Is there anything more I can do to help get this pull request accepted?

**Comment by technomancy** [comment]
I'd feel better if we had more than one tester, but I can merge it into master as-is if we can try to get more testers on it before cutting the actual release.

**Pull request merged**
